### ISSUE TITLE
The Demo Application is broken

### ISSUE THREAD

**Issue by talhaobject90** [EmberPittsburgh/ember-2-example#2]
The demo application (http://emberpittsburgh.github.io/ember-2-example/#/chat/1) is broken
Failed to find a valid digest in the 'integrity' attribute for resource. Please fix it.

I found only this one as a reliable example for ember 2.0 app .

**Comment by alexlafroscia** [comment]
Hmm, interesting.  I'm seeing that issue in Chrome now as well, but I haven't changed anything here since I first built it.  I'll try to look into it and see what's going on.

**Comment by agarcia17** [comment]
thanks alexlafroscia! yeah this is the only reliable example i found for ember 2.x too!

**Comment by alexlafroscia** [comment]
If you're curious, this is what is causing the problem, it seems:

https://github.com/jonathanKingston/ember-cli-sri/issues/5

I'm going to try updating the dependency and rebuilding to see if that fixes it.  In the meantime, other browsers should work.
